# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vLkOr_ZwPpIlu94PyaW_FLB4J4eVNokt
"""

from flask import Flask, request, jsonify
import pandas as pd

# Load cleaned dataset
df = pd.read_csv("cleaned_players.csv")

# Convert names and clubs to lowercase for easy matching
df['name'] = df['name'].str.lower()
df['club'] = df['club'].str.lower()

app = Flask(__name__)

@app.route("/chat", methods=["POST"])
def chat():
    user_input = request.json.get("message", "").lower()

    # Example 1: Ask about a player's goals
    if "goals" in user_input:
        for name in df['name']:
            if name in user_input:
                goals = int(df[df['name'] == name]['goals'].values[0])
                return jsonify({"response": f"{name.title()} scored {goals} goals."})
        return jsonify({"response": "Player not found in the dataset."})

    # Example 2: Ask about a club's appearances
    elif "appearances" in user_input:
        for name in df['name']:
            if name in user_input:
                appearances = int(df[df['name'] == name]['appearances'].values[0])
                return jsonify({"response": f"{name.title()} made {appearances} appearances."})
        return jsonify({"response": "Player not found in the dataset."})

    # Add more patterns here...

    return jsonify({"response": "Sorry, I didn't understand the question."})

if __name__ == "__main__":
    app.run(debug=True)