# -*- coding: utf-8 -*-
"""etl

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u1XjJxDGZGD3M4UYjH5Kv7iK_1fkCxYe
"""

import pandas as pd

def run_etl():
    # Step 1: Extract raw data
    input_path = "dataset - 2020-09-24.csv"
    df = pd.read_csv(input_path)

    # Step 2: Transform
    df.columns = df.columns.str.lower().str.replace(" ", "_")

    numeric_cols = df.select_dtypes(include="number").columns
    df[numeric_cols] = df[numeric_cols].fillna(0)

    # Optional: standardize name/club formatting
    if "name" in df.columns:
        df["name"] = df["name"].str.lower()
    if "club" in df.columns:
        df["club"] = df["club"].str.lower()

    # Step 3: Load
    output_path = "cleaned_players.csv"
    df.to_csv(output_path, index=False)
    print(f"ETL complete. Cleaned file saved as {output_path}")

if __name__ == "__main__":
    run_etl()